[emubox]
image=ghcr.io/ublue-os/arch-toolbox:latest
home=$HOME/.emubox
additional_packages="archlinux-keyring noto-fonts noto-fonts-cjk"
additional_packages="cartridges zenity"
# appimage support packages
additional_packages="fuse2 jack2 glibmm libxss libxv libxcomposite"
additional_packages="harfbuzz gdk-pixbuf2 libxrandr libxinerama libxcursor libxi libxkbcommon fribidi"
additional_packages="fontconfig libxdamage libthai nss atk cups gtk3"
entry=false
start_now=true
replace=true

[emubox-debug]
clone=emubox
home=$HOME/.emubox-debug
entry=false 