#!/bin/bash

if [ "$EUID" == 0 ]
    then echo "Please don't run this a root."
    exit
fi

mkdir -p $HOME/.local/applications
mkdir $HOME/.local/bin
mkdir -p $HOME/.emubox/launchers
# mkdir $HOME/.emubox/apps

distrobox create \
    -Y \
    --no-entry \
    --name emubox \
    --image ghcr.io/ublue-os/arch-distrobox:latest 

distrobox enter emubox -- \
    sudo pacman -Syu --noconfirm \
        archlinux-keyring \
        noto-fonts \
        noto-fonts-cjk
distrobox enter emubox -- \
    sudo locale-gen "$LANG" 

echo "Downloading emubox package manager..."
curl -o $HOME/.local/bin/emubox https://emubox.wolves-are.gay/emubox
chmod +x $HOME/.local/bin/emubox
echo "Emubox installation complete! Run 'emubox init' to get started"
