#!/bin/bash

LATEST_VER=$(curl -s https://emubox.wolves-are.gay/latest | tr -d "\n")
CURRENT_VER=$($HOME/.local/bin/emubox -v)

if [ $LATEST_VER != $CURRENT_VER ]; then
    echo "Updating emubox package manager..."
    curl -o $HOME/.local/bin/emubox https://emubox.wolves-are.gay/emubox
else
    echo "Package manager up to date!"
fi

echo "Updating emubox container and apps..."
distrobox enter emubox -- paru -Syu