on:
    workflow_dispatch:

    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                bun-version: latest

            - name: Setup Just
              uses: extractions/setup-just@v3


            - name: Install Modules and Build
              run: |
                bun i --production
                just build --define="_SHA='${{ github.sha }}'"
            
            - name: Copy Installer and README
              run: |
                cp install dist/install
                cp README.md dist/README.md
                cp emubox.ini dist/emubox.ini
                echo "emubox.wolves-are.gay" >> dist/CNAME
                echo $(bun dev -v) >> dist/latest

            - name: Push to Dist
              uses: s0/git-publish-subdir-action@develop
              env:
                REPO: self
                BRANCH: dist
                FOLDER: dist
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                MESSAGE: "[`{sha}`] {msg}"
         
