on:
    workflow_dispatch:

    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                bun-version: latest

            - name: Install Modules and Build
              run: |
                bun i
                bun build-main
                bun build-installer

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: emubox
                path: dist/
         