on:
    workflow_dispatch:

    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                bun-version: latest

            - name: Install Modules and Build
              run: |
                bun i
                bun build-main
                bun build-installer

            - name: Push to Dist
              uses: s0/git-publish-subdir-action@develop
              env:
                REPO: self
                BRANCH: dist
                FOLDER: dist
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                MESSAGE: "{msg} `{sha}`"
         
